apiVersion: v1
kind: Pod
metadata:
  name: rotf3-pod
  labels:
    app: rotf3
spec:
  containers:
  - name: rotf3-container
    image: rq62680/rotf3:latest
    imagePullPolicy: IfNotPresent
    #   command: ["echo", "Hello World!"]
    #    resources:
    #      requests:
    #        memory: "512Mi"
    #      limits:
    #        memory: "2048Mi"
  nodeSelector:
    kubernetes.io/hostname: haiguang04
  restartPolicy: Never
