apiVersion: v1
kind: Pod
metadata:
  name: rotf2-pod
  labels:
    app: rotf2
spec:
  containers:
  - name: rotf2-container
    image: rotf2:latest
    imagePullPolicy: Never
    #   command: ["echo", "Hello World!"]
    #    resources:
    #      requests:
    #        memory: "512Mi"
    #      limits:
    #        memory: "2048Mi"
    #  nodeSelector:
    #    kubernetes.io/hostname: shuguang03
  restartPolicy: Never
